server:
  port: 8082

spring:
  application:
    name: task_planner_scheduler
  config:
    import: classpath:additional-application.properties

  datasource:
    url: jdbc:postgresql://localhost:5432/planner
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:29092